import "./globals.css";
import Header from "@/components/Header";
import localFont from "next/font/local";

export const clashDisplay = localFont({
  src: [
    {
      path: "./fonts/ClashDisplay-Extralight.ttf",
      weight: "200",
      style: "normal",
    },
    {
      path: "./fonts/ClashDisplay-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/ClashDisplay-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/ClashDisplay-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/ClashDisplay-Semibold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/ClashDisplay-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  display: "swap",
});

export const metadata = {
  title: "Awwwards-2",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en">
      <body className={`${clashDisplay.className} antialiased`}>
      <Header />
          <main className="min-h-[200vh] bg-white relative z-40 w-full">
            {children}
          </main>
      </body>
    </html>
  );
}
